{% set version = "3.5.6" %}
{% set md5 = "16b0c2319eb1aa8da1aae917e84e0680" %}

package:
  name: python
  version: {{ version }}

source:
  - url: http://www.stackless.com/binaries/stackless-356-export.tar.xz
    md5: {{ md5 }}
    patches:
      - 0001-backport-Python-3.6-_PYTHON_SYSCONFIGDATA_NAME-also-.patch
      - 0002-Issue-21122-Fix-LTO-builds-on-OS-X.-Patch-by-Brett-C.patch
      - 0003-Add-Anaconda-Distribution-version-logic.patch
      - 0004-Darwin-Omit-PYTHONFRAMEWORK-site-packages.patch
      - 0005-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - 0006-Win32-distutils-Also-look-for-executable.bat.patch
      # TODO :: This breaks conda activate and deactivate.
      - 0007-Win32-Ensure-Library-bin-is-in-os.environ-PATH.patch
      - 0008-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - 0009-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - 0010-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - 0011-Support-cross-compiling-byte-code.patch
      - 0012-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - 0013-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - 0014-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - 0015-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - 0016-Fix-macOS-test_asyncio-from-https-github.com-python-.patch
      - 0017-Disable-new-dtags-in-unixccompiler.py.patch
      - 0018-Fix-cross-compilation-on-Debian-based-distros.patch

build:
  number: 0
  # Windows has issues updating python if conda is using files itself.
  # Copy rather than link.
  no_link:
    - DLLs/_ctypes.pyd  # [win]
    - bin/python3.5     # [unix]
  # script_env:
  #   - python_branding
  # We delete the shared libraries.
  ignore_run_exports:   # [unix]
    - bzip2             # [unix]
  skip: True            # [win and vc != 14]
  features:
    - stackless

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - svn                                # [win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - make                               # [unix]
    - pkg-config                         # [unix]
  host:
    - bzip2                              # [unix]
    - sqlite                             # [unix]
    - xz                                 # [unix]
    - zlib                               # [unix]
    - openssl                            # [unix]
    - readline                           # [unix]
    - tk                                 # [unix]
    - ncurses                            # [unix]
    - libffi                             # [unix]

test:
  commands:
    - python -V
    - python3 -V            # [unix]
    - 2to3 -h
    - pydoc -h
    - python3-config --help  # [unix]
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    -  _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"  # [linux64]
  requires:
    - stackless

about:
  home: http://www.stackless.com/
  license: PSF
  license_file: LICENSE
  summary: General purpose programming language
  description: |
    Python is a widely used high-level, general-purpose, interpreted, dynamic
    programming language. Its design philosophy emphasizes code
    readability, and its syntax allows programmers to express concepts in
    fewer lines of code than would be possible in languages such as C++ or
    Java. The language provides constructs intended to enable clear programs
    on both a small and large scale.
  doc_url: https://stackless.readthedocs.io/en/3.5-slp/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  dev_url: https://github.com/stackless-dev/stackless

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - mingwandroid
    - msarahan
    - pelson
    - ocefpaf
    - akruis
