# This file was not generated automatically but written by hand

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable for anaconda/stackless
    - secure: "kTfuqCnVDbVdoJlgV4FtxIPpPTK4j1xwAGURuTPvM8khc5HDSyV5Bg7cihunpAWPwUQODMCuXHU7gOFKZ/Caym+VCz3bRCsOXUKioR04WQcy8S2Md8CBj8wLKadwO3lRRBvtIb+w4dDEue/vyDMHIXsNS284sPAvuoWlxMmdjD03u1oLzhAAy5eR5Fsd+1Jm+Pe1MOkeCNhJZppiJeJ9ZVHS8RmruwXyBsDRYf7abMkyykB0CNVcc/P7EAApwBZJ/XG3YCEgt/bzPmAFMWZ8ujc/g4GzsL4ZLuTBfCybCJveTEYCVuxIDvl4rBmCWflp4hPi4X/OnRcjlsc2z4QkZ85WkqUlxSXaJvWOleO0PhL3+b2NZ0stqsCrMYWZXfTjRLkk4Nx+zYvRP9YjQXzbt2DyxTSRigXrbIC6pvddXNaggDBwXtT23VjnjTmjAz20JU+F/drDamoTKzsx8e2M8+E+23gu1f+1opQ0dYrjrkAydTXTBEDjaGzXfGjOYnXVUNXQgwD1toXyP5FTziRA0Gt8e1pDGEFfAInWd5o5fyrJzCrV4GoE8dLPNH4kF27sC6bQBpKq05aKsJrKKWkT3yND6c/gHe+HTsGsX0jl3TW0WZseej8ndtTDCNATLpb7kOCQYvhsAibnGQ7cpOajonzaEE5Frj6kYV9yDTSQ+3k="

before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate
      conda config --remove channels local
      conda config --set add_pip_as_python_dependency False
      conda config --add channels stackless
      conda config --set show_channel_urls true
      conda config --set anaconda_upload no
      conda install --yes --quiet conda-build xz python
      conda install -c anaconda anaconda-client
      python -m pip install base91

script:
  - |
    { ( while sleep 30 ; do echo "." ; done ) < /dev/null 2>/dev/null & } && DOTPRINTER_PID=$! && \
    conda build ./recipe --python=${CONDA_PY} > build.log ; EXIT_CODE=$?
    kill $DOTPRINTER_PID && wait $DOTPRINTER_PIT
    echo "last 200 lines of output:"
    tail -n 200 build.log
    echo ""
    if [ $EXIT_CODE -eq 0 ] ; then
       echo "Created artefact:"
       conda build --output ./recipe
    else
       echo "conda build failed with exit code: $EXIT_CODE"
    fi
    echo ""
    echo "xz compressed and base91 encoded output of the build follows:"
    xz -z -c -9 -e < build.log | python -c 'import base91,sys;print(base91.encode(getattr(sys.stdin,"buffer",sys.stdin).read()))' | fold
    echo ""
    test $EXIT_CODE -eq 0

after_success:
  - |
    ARTEFACT="$(conda build --output ./recipe)"
    test -f "$ARTEFACT" && test "x$BINSTAR_TOKEN" != "x" && anaconda --token "$BINSTAR_TOKEN" upload "$ARTEFACT" --no-progress --label test


deploy:
  skip_cleanup: true

